---
# tasks file for vm-rebootguest

- name: Reboot a virtual machine by uuid
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ validate_certs | default('False') }}"
    uuid: "{{ vm_uuid }}"
    state: rebootguest
